services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - ML_SERVICE_URL=http://ml-service:8000/predict
    depends_on:
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
